server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/hooliguns
    username: hooliguns
    password: hooliguns
  data:
    mongodb:
      uri: mongodb://localhost:27017/hooliguns

hooliguns:
  admin:
    username: ${HOOLIGUNS_ADMIN_USERNAME:s000000}
    password: ${HOOLIGUNS_ADMIN_PASSWORD:admin}
  immortal:
    username: ${HOOLIGUNS_IMMORTAL_USERNAME:s999999}
    password: ${HOOLIGUNS_IMMORTAL_PASSWORD:immortal}
